### ISSUE TITLE
Timestamps Change

### ISSUE THREAD

**Issue by Juice805** [skiplagged/pokemongo-python#16]
Using this API I check for rare pokemon and store them in a list. To verify that each pokemon returned is unique I check long, lat, timestamp and ID, however even when the ID, long and lat are the same, sometimes the timestamp returned from the server has a different value, giving me duplicates on my list. I've seen the values vary by up to 5 seconds

**Comment by aktarer** [comment]
That's because Niantic's doesn't return timestamps so we have to compute them. As such, there's a little variation from latency. You can just use ID, lng, and lat to identify.

**Comment by Juice805** [comment]
How accurate are the lat, long? I'm using .00002 tolerance

**Comment by aktarer** [comment]
Very accurate
