### ISSUE TITLE
Problems running on ubuntu

### ISSUE THREAD

**Issue by jstefox** [skiplagged/pokemongo-python#2]
Hi, I am running the latest Ubuntu Dev. I ran the script, and it runs correctly (screen attached), however neither localhost:8000 nor 0.0.0.0:8000 show anything on Mozilla Firefox (standard Firefox that comes with Ubuntu, updated to latest version). The title of the page correctly displays 'PokeScreen' but the page is empty. Inspecting it in Firefox reveals that it has a script, and Firebug reports no issues. I have tried running Firefox in safe mode, disabling addons and disabling various security measures, thinking it's an issue with Firefox rather than with the script, but to no avail. Any and all help will be very much appreciated. I attach the screenshot of the script running
![pokemongo](https://cloud.githubusercontent.com/assets/20546221/16967915/967b25a8-4e03-11e6-9f3b-eb33f60a9aae.png)

**Comment by aktarer** [comment]
Wrong git repo
