### ISSUE TITLE
Still seeing no data after running locally

### ISSUE THREAD

**Issue by blackdynamo** [skiplagged/pokemongo-python#3]
So I have the script running, but I am not seeing any updated data on skipslagged.com
http://skiplagged.com/api/pokemon.php?bounds=51.023227,-114.116278,51.055393,-114.032850

Config:
`bounds = ((51.023227, -114.116278),(51.055393, -114.032850))`

Output:
```
1468982434.42 moving player
1468982434.63 found 2 pokemon
Paras [46]: 51.041087, -114.083116, 494 seconds left
Hypno [97]: 51.041099, -114.081874, 285 seconds left
1468982435.14 moving player
1468982435.87 moving player
1468982436.12 found 3 pokemon
Zubat [41]: 51.043924, -114.078052, 206 seconds left
Pidgey [16]: 51.043403, -114.079247, 608 seconds left
Pidgey [16]: 51.043009, -114.079862, 526 seconds left
1468982436.62 moving player
1468982437.34 moving player
1468982438.08 moving player
1468982438.3 found 1 pokemon
```

**Comment by aktarer** [comment]
Should be fixed now! Sorry about that

**Comment by blackdynamo** [comment]
@aktarer Looks good. Looks like whatever change you made fixed it. I am assuming it was a change on the skiplagged mapping side of things as I didn't see any changes to this repo.

Thanks :)

**Comment by blackdynamo** [comment]
@aktarer Seems to have gone down again. I am still reporting but no data showing on the map. Nothing showing for Central Park, NY either.

http://skiplagged.com/api/pokemon.php?address=central%20park,%20new%20york,%20ny

**Comment by aktarer** [comment]
We had a little outage, should be back now. Thanks
